spring:
  application:
    name: EmailNotificationMicroservice

  datasource:
    username: test
    password: test
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true


  kafka:
    consumer:
      auto-offset-reset: latest
      bootstrap-servers: localhost:9092, localhost:9094
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: product-create-events
      properties:
        spring:
          json:
            trusted:
              packages: by.itacademy.library.event
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 0
